### ISSUE TITLE
Update & deploy for Alex

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadash#2]
- [x] Block finality
- [ ] Short addresses
- [x] Validator invulnerability
- [ ] Move balances
- [ ] Update polkadot

**Comment by ddorgan** [comment]
Are all your changes pushed? Not seeing port 40510 open when building this....

**Comment by gavofyork** [comment]
should be working now...

**Comment by ddorgan** [comment]
Any idea on this? I don't see it locally, or with the docker container on a linux host, but I see it in kubernetes....

```
yarn run v1.12.3
warning package.json: License should be a valid SPDX license expression
$ cd client && yarn run build && cd .. && node server.js
warning package.json: License should be a valid SPDX license expression
warning ../package.json: License should be a valid SPDX license expression
$ webpack --mode production
Hash: 1149990eab40402e536d
Version: webpack 4.28.4
Time: 17462ms
Built at: 01/23/2019 7:37:59 PM
                               Asset      Size  Chunks                    Chunk Names
82f60bd0b94a1ed68b1e6e309ce2e8c3.svg   105 KiB          [emitted]         
8e3c7f5520f5ae906c6cf6d7f3ddcd19.eot   104 KiB          [emitted]         
962a1bf31c081691065fe333d9fa8105.svg   382 KiB          [emitted]  [big]  
a1a749e89f578a49306ec2b055c073da.svg   496 KiB          [emitted]  [big]  
b87b9ba532ace76ae9f6edfe9f72ded2.ttf   103 KiB          [emitted]         
                           bundle.js  2.44 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = bundle.js
  [6] (webpack)/buildin/global.js 472 bytes {0} [built]
[127] crypto (ignored) 15 bytes {0} [built]
[136] util (ignored) 15 bytes {0} [built]
[138] util (ignored) 15 bytes {0} [built]
[184] ./node_modules/polkadot-identicon/node_modules/oo7-substrate/src/srml sync ^\.\/.*$ 321 bytes {0} [optional] [built]
[200] ./node_modules/oo7-substrate/src/srml sync ^\.\/.*$ 321 bytes {0} [optional] [built]
[202] ./src/index.js + 2 modules 17.7 KiB {0} [built]
      | ./src/index.js 211 bytes [built]
      | ./src/app.jsx 12.3 KiB [built]
      |     + 1 hidden module
    + 196 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  962a1bf31c081691065fe333d9fa8105.svg (382 KiB)
  a1a749e89f578a49306ec2b055c073da.svg (496 KiB)
  bundle.js (2.44 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (2.44 MiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Error reading config.json: Error: ENOENT: no such file or directory, open '/app/config.json'. Using defaults
Listening on port 3000!
Connection open
/app/node_modules/oo7-substrate/src/bonds.js:37
	r.apis.forEach(([id, version]) => apis[String.fromCharCode.apply(null, id)] = version)
	                                                           ^

TypeError: CreateListFromArrayLike called on non-object
    at r.apis.forEach (/app/node_modules/oo7-substrate/src/bonds.js:37:61)
    at Array.forEach (<anonymous>)
    at Proxy.r (/app/node_modules/oo7-substrate/src/bonds.js:37:9)
    at Object.callback (/app/node_modules/oo7-substrate/src/subscriptionBond.js:20:19)
    at WebSocket.ws.onmessage (/app/node_modules/oo7-substrate/src/nodeService.js:84:47)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:741:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:417:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by gavofyork** [comment]
yeah that's when it's on an old oo7-substrate

**Comment by gavofyork** [comment]
will need updating to the very latest 0.4.13 - i just pushed the fix to GH
